const ADD_ITEM_IN_CART = "ADD_ITEM_IN_CART";
const SHOW_CART_DLG = "SHOW_CART_DLG";
const DELETE_CART_ITEM = "DELETE_CART_ITEM";
const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";

export {
  ADD_ITEM_IN_CART,
  SHOW_CART_DLG,
  DELETE_CART_ITEM,
  UPDATE_CART_ITEM_QUANTITY,
};
